"""Integration tests for `tusk init-write-manifest-files` (TASK-214).

The fresh-project /tusk-init Step 8.5 and the post-init `tusk add-lib` path
both call this writer to materialize a lib's `manifest_files` block. These
tests pin the user-visible contract end-to-end:

1. `create_only` writes a missing file with the exact bytes from the spec
   and reports it under `wrote`.
2. Re-running against an unchanged tree is a no-op — every entry lands in
   `skipped` and the summary line reports "skipped N existing".
3. `append_if_missing` adds the content to an existing file only when it
   isn't already present (idempotent line append).
"""

import json
import os
import subprocess

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TUSK_BIN = os.path.join(REPO_ROOT, "bin", "tusk")


def _write_manifest(tmp_path, spec, *, repo_root=None, via="spec"):
    """Run `tusk init-write-manifest-files` with the given JSON spec; return parsed stdout JSON.

    `via` selects how the spec is delivered to the writer:
      - "spec" (default) — passed inline with --spec '<json>'
      - "spec-file"      — written to a tmp file and passed with --spec-file <path>
    """
    db_file = tmp_path / "tusk" / "tasks.db"
    env = {**os.environ, "TUSK_DB": str(db_file)}
    args = [TUSK_BIN, "init-write-manifest-files"]
    if via == "spec":
        args += ["--spec", json.dumps(spec)]
    elif via == "spec-file":
        spec_path = tmp_path / "manifest-spec.json"
        spec_path.write_text(json.dumps(spec), encoding="utf-8")
        args += ["--spec-file", str(spec_path)]
    else:
        raise ValueError(f"unknown via mode: {via!r}")
    if repo_root is not None:
        args += ["--repo-root", str(repo_root)]
    result = subprocess.run(
        args,
        cwd=str(tmp_path),
        env=env,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result


@pytest.fixture()
def project_root(tmp_path):
    """A tmp directory that mimics a target project root."""
    (tmp_path / "tusk").mkdir()
    return tmp_path


def test_bootstrap_manifest_create_only_writes_missing_file(project_root):
    """create_only mode materializes a missing file with exact content."""
    spec = [
        {"path": "Package.swift", "content": "// generated by tusk\nimport PackageDescription\n"},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 0, f"writer failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)

    assert payload["success"] is True
    assert [w["path"] for w in payload["wrote"]] == ["Package.swift"]
    assert payload["skipped"] == []
    assert payload["summary"] == "wrote 1 file, skipped 0 existing"

    written = (project_root / "Package.swift").read_text(encoding="utf-8")
    assert written == "// generated by tusk\nimport PackageDescription\n"


def test_bootstrap_manifest_create_only_skips_existing_file(project_root):
    """create_only must not overwrite a file that already exists — re-run is a no-op."""
    target = project_root / "Package.swift"
    target.write_text("// user content — must be preserved\n", encoding="utf-8")

    spec = [
        {"path": "Package.swift", "content": "// from tusk bootstrap\n"},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 0, f"writer failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)

    assert payload["wrote"] == []
    assert [s["path"] for s in payload["skipped"]] == ["Package.swift"]
    assert payload["skipped"][0]["reason"] == "already exists"
    assert payload["summary"] == "wrote 0 files, skipped 1 existing"

    # User content survives intact.
    assert target.read_text(encoding="utf-8") == "// user content — must be preserved\n"


def test_bootstrap_manifest_rerun_is_noop(project_root):
    """Calling the writer twice with the same spec leaves the tree untouched on the second pass."""
    spec = [
        {"path": "tusk/conventions/python.md", "content": "# Python conventions\n\n- Prefer structured logging.\n"},
        {"path": "Package.swift", "content": "// pkg\n"},
    ]
    first = _write_manifest(project_root, spec, repo_root=project_root)
    assert first.returncode == 0
    first_payload = json.loads(first.stdout)
    assert len(first_payload["wrote"]) == 2

    second = _write_manifest(project_root, spec, repo_root=project_root)
    assert second.returncode == 0
    second_payload = json.loads(second.stdout)
    assert second_payload["wrote"] == []
    assert {s["path"] for s in second_payload["skipped"]} == {
        "tusk/conventions/python.md",
        "Package.swift",
    }
    assert second_payload["summary"] == "wrote 0 files, skipped 2 existing"


def test_bootstrap_manifest_append_if_missing_appends_when_absent(project_root):
    """append_if_missing adds the content to an existing file when it isn't already present."""
    requirements = project_root / "requirements.txt"
    requirements.write_text("flask==3.0.0\n", encoding="utf-8")

    spec = [
        {"path": "requirements.txt", "content": "gioe-libs>=0.4\n", "mode": "append_if_missing"},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 0, f"writer failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)

    assert [w["path"] for w in payload["wrote"]] == ["requirements.txt"]
    assert payload["skipped"] == []
    assert requirements.read_text(encoding="utf-8") == "flask==3.0.0\ngioe-libs>=0.4\n"


def test_bootstrap_manifest_append_if_missing_skips_when_present(project_root):
    """append_if_missing must not duplicate a line that's already in the target file."""
    requirements = project_root / "requirements.txt"
    requirements.write_text("flask==3.0.0\ngioe-libs>=0.4\n", encoding="utf-8")

    spec = [
        {"path": "requirements.txt", "content": "gioe-libs>=0.4\n", "mode": "append_if_missing"},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 0, f"writer failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)

    assert payload["wrote"] == []
    assert [s["path"] for s in payload["skipped"]] == ["requirements.txt"]
    assert payload["skipped"][0]["reason"] == "content already present"
    # Idempotent — file is byte-identical.
    assert requirements.read_text(encoding="utf-8") == "flask==3.0.0\ngioe-libs>=0.4\n"


def test_bootstrap_manifest_append_if_missing_creates_file_when_absent(project_root):
    """append_if_missing falls back to create when the target file doesn't exist yet."""
    spec = [
        {"path": "requirements.txt", "content": "gioe-libs>=0.4\n", "mode": "append_if_missing"},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 0
    payload = json.loads(result.stdout)

    assert [w["path"] for w in payload["wrote"]] == ["requirements.txt"]
    assert (project_root / "requirements.txt").read_text(encoding="utf-8") == "gioe-libs>=0.4\n"


def test_bootstrap_manifest_rejects_path_traversal(project_root):
    """Path traversal must be rejected by the writer even though the validator already
    caught it upstream — defense in depth for the post-init add-lib path."""
    spec = [{"path": "../etc/passwd", "content": "x"}]
    result = _write_manifest(project_root, spec, repo_root=project_root)
    assert result.returncode == 1, f"expected failure, got success:\nSTDOUT: {result.stdout}"
    payload = json.loads(result.stdout)
    assert payload["success"] is False
    assert ".." in payload["error"]


def test_bootstrap_manifest_spec_file_writes_file(project_root):
    """--spec-file reads the JSON spec from a file and writes the same way --spec does.

    Pins the contract for callers passing manifest content too large for argv (multi-KB
    convention templates can otherwise approach the platform's ARG_MAX limit)."""
    spec = [
        {"path": "tusk/conventions/large.md", "content": "# Conventions\n\n" + ("- rule\n" * 200)},
    ]
    result = _write_manifest(project_root, spec, repo_root=project_root, via="spec-file")
    assert result.returncode == 0, f"writer failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)

    assert payload["success"] is True
    assert [w["path"] for w in payload["wrote"]] == ["tusk/conventions/large.md"]
    written = (project_root / "tusk" / "conventions" / "large.md").read_text(encoding="utf-8")
    assert written == "# Conventions\n\n" + ("- rule\n" * 200)


def test_bootstrap_manifest_spec_and_spec_file_are_mutually_exclusive(project_root):
    """argparse must reject passing both --spec and --spec-file."""
    db_file = project_root / "tusk" / "tasks.db"
    env = {**os.environ, "TUSK_DB": str(db_file)}
    spec_path = project_root / "manifest-spec.json"
    spec_path.write_text("[]", encoding="utf-8")
    result = subprocess.run(
        [
            TUSK_BIN, "init-write-manifest-files",
            "--spec", "[]",
            "--spec-file", str(spec_path),
            "--repo-root", str(project_root),
        ],
        cwd=str(project_root),
        env=env,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    assert result.returncode == 1, f"expected failure, got:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
    payload = json.loads(result.stdout)
    assert payload["success"] is False
    assert "--spec" in payload["error"] and "--spec-file" in payload["error"]
    # argparse's own error message also lands on stderr — confirm the mutual-exclusion
    # branch fired (rather than some unrelated argparse failure).
    assert "not allowed with argument" in result.stderr
