"""Unit tests for tusk-glossary.py — markdown parser and renderer.

These exercise the pure-Python helpers that don't need a DB:
- parse_glossary_md() must round-trip the canonical entry shape
- render_glossary_md() must emit the <!-- generated --> header and a
  deterministic section block per entry
- _normalize_topics() must trim whitespace and drop empty tags
"""

import importlib.util
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCRIPT_DIR = os.path.join(REPO_ROOT, "bin")


def _load_glossary():
    sys.path.insert(0, SCRIPT_DIR)
    spec = importlib.util.spec_from_file_location(
        "tusk_glossary",
        os.path.join(SCRIPT_DIR, "tusk-glossary.py"),
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


tusk_glossary = _load_glossary()


SAMPLE_MD = """\
# Tusk Glossary

Header text here.

---

## chain head

A task that is ready to start (no blockers).

→ See `v_chain_heads`.

---

## WSJF

Weighted Shortest Job First — priority scoring.

→ See [`DOMAIN.md`](DOMAIN.md#wsjf).

---

## bare-no-see-also

Definition without a see-also pointer.
"""


class TestParseGlossaryMd:

    def test_extracts_three_entries(self):
        entries = tusk_glossary.parse_glossary_md(SAMPLE_MD)
        assert len(entries) == 3

    def test_first_entry_term_and_see_also(self):
        entries = tusk_glossary.parse_glossary_md(SAMPLE_MD)
        term, definition, see_also = entries[0]
        assert term == "chain head"
        assert definition == "A task that is ready to start (no blockers)."
        assert see_also == "`v_chain_heads`"

    def test_wsjf_see_also_strips_arrow(self):
        entries = tusk_glossary.parse_glossary_md(SAMPLE_MD)
        _, _, see_also = entries[1]
        assert see_also == "[`DOMAIN.md`](DOMAIN.md#wsjf)"

    def test_entry_without_see_also(self):
        entries = tusk_glossary.parse_glossary_md(SAMPLE_MD)
        term, definition, see_also = entries[2]
        assert term == "bare-no-see-also"
        assert definition == "Definition without a see-also pointer."
        assert see_also is None

    def test_empty_section_skipped(self):
        md = "## empty-term\n\n---\n\n## real-term\n\nHas a definition.\n"
        entries = tusk_glossary.parse_glossary_md(md)
        assert [e[0] for e in entries] == ["real-term"]

    def test_multiline_definition_preserved(self):
        md = """\
## term

First paragraph.

Second paragraph still part of the definition.

→ See ref.
"""
        entries = tusk_glossary.parse_glossary_md(md)
        _, definition, _ = entries[0]
        assert "First paragraph." in definition
        assert "Second paragraph" in definition


class TestRenderGlossaryMd:

    def test_starts_with_generated_header(self):
        rendered = tusk_glossary.render_glossary_md([("term", "def", None, None)])
        assert rendered.splitlines()[0].startswith(
            "<!-- generated by `tusk glossary export`"
        )

    def test_emits_term_heading_and_definition(self):
        rendered = tusk_glossary.render_glossary_md([
            ("chain head", "A task that is ready.", "`v_chain_heads`", None),
        ])
        assert "## chain head" in rendered
        assert "A task that is ready." in rendered
        assert "→ See `v_chain_heads`." in rendered

    def test_omits_see_also_when_null(self):
        rendered = tusk_glossary.render_glossary_md([
            ("term", "Plain definition.", None, None),
        ])
        assert "→ See" not in rendered

    def test_separator_between_entries_but_not_after_last(self):
        rendered = tusk_glossary.render_glossary_md([
            ("a", "first", None, None),
            ("b", "second", None, None),
        ])
        # Between entries there is a `---` separator. After the last entry,
        # there should be no trailing `---` (the file ends after the body).
        # The body section excludes the leading "---" under the title.
        body = rendered.split("Canonical definitions for terms")[1]
        # Count separator lines after the title block.
        separators = [line for line in body.splitlines() if line == "---"]
        # Exactly one between the title block and the first entry, and one
        # between the two entries — so two total in the body region.
        assert separators.count("---") == 2

    def test_round_trip_parse_then_render_preserves_entries(self):
        original = [
            ("alpha", "first def.", "`alpha-ref`", None),
            ("beta", "second def.", None, None),
            ("gamma", "third def.", "[`X`](x.md)", None),
        ]
        rendered = tusk_glossary.render_glossary_md(original)
        reparsed = tusk_glossary.parse_glossary_md(rendered)
        assert reparsed == [
            ("alpha", "first def.", "`alpha-ref`"),
            ("beta", "second def.", None),
            ("gamma", "third def.", "[`X`](x.md)"),
        ]


class TestNormalizeTopics:

    def test_none_passthrough(self):
        assert tusk_glossary._normalize_topics(None) is None

    def test_strips_whitespace(self):
        assert tusk_glossary._normalize_topics(" a , b , c ") == "a,b,c"

    def test_drops_empty_tags(self):
        assert tusk_glossary._normalize_topics("a,,b,,") == "a,b"

    def test_all_empty_returns_none(self):
        assert tusk_glossary._normalize_topics(",,") is None
